command to connect below db - make sure after docker-compose wait for 10-15 min for initialization of mysql
# mysql -h 127.0.0.1 -u prashant -p firstdb


-----------------------------------------------------------------------------------------------------------------------------------------------------------


version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: firstdb
      MYSQL_USER: prashant
      MYSQL_PASSWORD: prashant
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:




  ----------------------------------------------------------------------------------------------------------------------------------

  -- init.sql

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);

INSERT INTO users (username, email) VALUES
    ('user1', 'user1@example.com'),
    ('user2', 'user2@example.com');
